### ISSUE TITLE
Errors are not shown?

### ISSUE THREAD

**Issue by Gerben321** [SymfonyCasts/dynamic-forms#20]
I'm trying to add a dynamic form and render with SF live component. But my validation errors are not shown?

When typing a wrong value in the pricetype I get this:
![image](https://github.com/SymfonyCasts/dynamic-forms/assets/24865452/b2ce23b7-573e-4f04-8711-e86313d0929a)

But when I press the submit button the error is gone. But in the profiler I still see the validation error:
![image](https://github.com/SymfonyCasts/dynamic-forms/assets/24865452/0afd2943-3ca9-4ff1-a0ee-692f0be6f522)

The form also shows a red 1:
![image](https://github.com/SymfonyCasts/dynamic-forms/assets/24865452/19da21a8-7969-44c9-8ab6-e7af7600f3a8)

But when I check form errors there are none?
![image](https://github.com/SymfonyCasts/dynamic-forms/assets/24865452/f3bbaa57-c61d-4297-8018-b9156871189d)

It's a really basic form, what's going on here?

**Comment by WoutervanderLoopNL** [comment]
@Gerben321  how did you solve this? ive the same problem with the money field

**Comment by Gerben321** [comment]
Can you post your code? It's been a while so I can remember how I solved it. 😂

**Comment by WoutervanderLoopNL** [comment]
@Gerben321  basicly the same as you have/had: 

error ends up in the `__dynamic_error` field

![image](https://github.com/user-attachments/assets/311227b8-fc5a-4739-ac65-45985a654395)
![image](https://github.com/user-attachments/assets/7dd042ec-387e-4c7f-941b-b4dcd9ddbc7c)
![image](https://github.com/user-attachments/assets/cc60ae62-1e0d-4456-a435-08008025001c)

**Comment by WoutervanderLoopNL** [comment]
@Gerben321 think i found the same solution you did, and closed your issue by yourself: 

https://github.com/TheBigBrainsCompany/TbbcMoneyBundle/issues/130

**Comment by WoutervanderLoopNL** [comment]
@Gerben321  that only fixes the problem for the half part. 

The `DynamicFormBuilder`  has a `clearDataOnTransformationError()`  which clears all the transformation errors and put them in the `__dynamic_error` field.

how did you handled it?
