### ISSUE TITLE
Data option not working

### ISSUE THREAD

**Issue by bouvetb** [SymfonyCasts/dynamic-forms#26]
Hello, 
I'm trying to use the bundle to display selects only if previous value has been selected and select a default value in the list but when i use the 'data' parameters in my dependent form type no options is selected by default. I'm working with live components. 
Here is my dependent field declaration :
![image](https://github.com/SymfonyCasts/dynamic-forms/assets/38523023/2bf06e34-b092-44b9-9806-41aee64c2fb7)
If i'm in edit mode the data are populated well.
My form is configurated with no data_class

**Comment by Huluti** [comment]
Same for me. With this code, the domain field doesn't change its value when an other folder is selected:

```php
$builder->addDependent('domain', 'folder', function (DependentField $field, ?Folder $folder) {
            $field->add(EntityType::class, [
                'class' => Domain::class,
                'choice_label' => 'host',
                'choice_value' => fn (?Domain $entity): string => $entity ? $entity->getPublicId()->toRfc4122() : '',
                'choices' => $folder?->getTeam()->getDomains(),
                'label' => 'links.form.domain_label',
                'help' => 'links.form.domain_help',
                'required' => false,
                'data' => $folder?->getDomain(),
            ]);
        });
```

**Comment by momocode-de** [comment]
I have the same problem. Even if I pass the initial value to the domain data object, the value is removed as soon as my field becomes visible. Does anyone already have a solution or workaround?

**Comment by momocode-de** [comment]
I did some debugging and found out that it could be solved by an adjustment in the `ComponentWithFormTrait` of the UX Bundle. I created a new issue for this in the UX Bundle: https://github.com/symfony/ux/issues/2369

**Comment by sadikoff** [comment]
So can we consider that this issue is not related to dynamic-form and close it?

**Comment by bouvetb** [comment]
ok i close it
