### ISSUE TITLE
Symfonycasts\DynamicForms\DynamicFormBuilder::add is not compatible with Symfony\Component\Form\FormBuilderInterface::add 

### ISSUE THREAD

**Issue by fransweerts** [SymfonyCasts/dynamic-forms#5]
Hello,

I am using  symfony/form version: v5.4.26.
Symfonycasts\DynamicForms\DynamicFormBuilder::add is not compatible with Symfony\Component\Form\FormBuilderInterface::add.

The typehint for the parameter $child is not compatible.

`Symfony:
Compile Error: Declaration of Symfonycasts\DynamicForms\DynamicFormBuilder::add(Symfony\Component\Form\FormBuilderInterface|string $child, ?string $type = null, array $options = []): Symfony\Component\ErrorHandler\DebugClassLoader must be compatible with Symfony\Component\Form\FormBuilderInterface::add($child, ?string $type = null, array $options = [])`

**Comment by bocharsky-bw** [comment]
@fransweerts  #6 should fix it, could you please double-check it works for you?

**Comment by fransweerts** [comment]
@bocharsky-bw  There are other methods which have the same issue. I have made a PR: #7

**Comment by bocharsky-bw** [comment]
Cool, thank you for fixing it on Symfony 5.4
